/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fastfood;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.PieSectionLabelGenerator;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author hieupt
 */
public class IncomeSummary extends javax.swing.JFrame
{

    /**
     * Creates new form IncomeSummary
     */
    public IncomeSummary(int count)
    {
        initComponents();
        this.item_count = count;
        show_totalincome_number();
    }
    
    public void show_totalincome_number()
    {
        System.out.println("item_count " + Integer.toString(this.item_count));
        int[] soluongsp = new int[this.item_count + 1];
        for (int i = 0; i < soluongsp.length; i++)
            soluongsp[i] = 0;
        try
        {
            String dbURL = "jdbc:sqlserver://localhost:1433;databaseName=fastfood;integratedSecurity=true";
            Connection conn = DriverManager.getConnection(dbURL);
            String query = "Select fk_id_sp, soluong from thongke";
            PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            while (rs.next())
            {
                soluongsp[rs.getInt("fk_id_sp")] += rs.getInt("soluong");
            }
        } catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        for(int i = 1; i < soluongsp.length; i++)
        {
            System.out.println(soluongsp[i]);
        }
        // chon tu ban sanpham
        try
        {
            String dbURL = "jdbc:sqlserver://localhost:1433;databaseName=fastfood;integratedSecurity=true";
            Connection conn = DriverManager.getConnection(dbURL);
            String query = "Select * from sanpham";
            PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            while (rs.next())
            {
                soluongsp[rs.getInt("id_sp")] *= rs.getInt("giathanh");
            }
        } catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        int sum = 0;
        for (int i = 1; i < soluongsp.length; i++)
            sum += soluongsp[i];
        Label_totalincome_number.setText(Integer.toString(sum) + "000");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        Label_IncomeSummary = new javax.swing.JLabel();
        Button_byproduct = new javax.swing.JButton();
        Button_bydate = new javax.swing.JButton();
        Label_totalincome = new javax.swing.JLabel();
        Label_totalincome_number = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label_IncomeSummary.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Label_IncomeSummary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-us-dollar-40.png"))); // NOI18N
        Label_IncomeSummary.setText("Income Summary");

        Button_byproduct.setText(" BY PRODUCT");
        Button_byproduct.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                Button_byproductMouseClicked(evt);
            }
        });

        Button_bydate.setText("BY DATE");

        Label_totalincome.setText("Total Income");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(Label_IncomeSummary)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_totalincome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_totalincome_number, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Button_byproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(Button_bydate, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Label_IncomeSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Label_totalincome, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(Label_totalincome_number, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_bydate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_byproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_byproductMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Button_byproductMouseClicked
    {//GEN-HEADEREND:event_Button_byproductMouseClicked
        // TODO add your handling code here:
        int[] soluongsp = new int[this.item_count + 1];
        String[] tensp = new String[this.item_count + 1];
        
        for (int i = 0; i < soluongsp.length; i++)
            soluongsp[i] = 0;
        try
        {
            String dbURL = "jdbc:sqlserver://localhost:1433;databaseName=fastfood;integratedSecurity=true";
            Connection conn = DriverManager.getConnection(dbURL);
            String query = "Select fk_id_sp, soluong from thongke";
            PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            while (rs.next())
            {
                soluongsp[rs.getInt("fk_id_sp")] += rs.getInt("soluong");
            }
        } catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        for(int i = 1; i < soluongsp.length; i++)
        {
            System.out.println(soluongsp[i]);
        }
        // chon tu ban sanpham
        try
        {
            String dbURL = "jdbc:sqlserver://localhost:1433;databaseName=fastfood;integratedSecurity=true";
            Connection conn = DriverManager.getConnection(dbURL);
            String query = "Select * from sanpham";
            PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            while (rs.next())
            {
                soluongsp[rs.getInt("id_sp")] *= rs.getInt("giathanh");
                tensp[rs.getInt("id_sp")] = rs.getString("tensanpham");
            }
        } catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        PieChart_byproduct(soluongsp, tensp);
    }//GEN-LAST:event_Button_byproductMouseClicked
    
    void PieChart_byproduct(int[] soluong, String[] ten)
    {        
        DefaultPieDataset dataset = new DefaultPieDataset();
        for(int i = 1; i < soluong.length; i++)
        {
            dataset.setValue(ten[i], soluong[i]);
        }
        JFreeChart someChart = ChartFactory.createPieChart(
            "Income By Product", dataset, true, true, false);
        PiePlot plot = (PiePlot) someChart.getPlot();
//        plot.setSectionPaint(KEY1, Color.green);
//        plot.setSectionPaint(KEY2, Color.red);
//        plot.setExplodePercent(KEY1, 0.10);
//        plot.setSimpleLabels(true);

        PieSectionLabelGenerator gen = new StandardPieSectionLabelGenerator(
            "{0}: {1} ({2})", new DecimalFormat("0"), new DecimalFormat("0%"));
        plot.setLabelGenerator(gen);

        ChartFrame f = new ChartFrame("Test", someChart);
//        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        f.add(new ChartPanel(someChart) {
//            @Override
//            public Dimension getPreferredSize() {
//                return new Dimension(400, 300);
//            }
//        });
        f.pack();
//        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(IncomeSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(IncomeSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(IncomeSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(IncomeSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new IncomeSummary(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_bydate;
    private javax.swing.JButton Button_byproduct;
    private javax.swing.JLabel Label_IncomeSummary;
    private javax.swing.JLabel Label_totalincome;
    private javax.swing.JLabel Label_totalincome_number;
    // End of variables declaration//GEN-END:variables
    int item_count;
}
