/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fastfood;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author hieupt
 */
public class LoginForm extends javax.swing.JFrame
{

    /**
     * Creates new form LoginForm
     */
    public LoginForm()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        Label_FormName = new javax.swing.JLabel();
        Label_UsrName = new javax.swing.JLabel();
        Label_Password = new javax.swing.JLabel();
        Button_Submit = new javax.swing.JButton();
        Text_UsrName = new javax.swing.JTextField();
        PasswordField_Password = new javax.swing.JPasswordField();
        Label_LoginInf = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label_FormName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Label_FormName.setText("Login");

        Label_UsrName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-user-50.png"))); // NOI18N
        Label_UsrName.setText("Username");

        Label_Password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-password-50.png"))); // NOI18N
        Label_Password.setText("Password");

        Button_Submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-login-50.png"))); // NOI18N
        Button_Submit.setText("Submit");
        Button_Submit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Button_SubmitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-online-shop-100.png"))); // NOI18N
        jLabel1.setText("Shop Management App");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Button_Submit)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_UsrName)
                            .addComponent(Label_Password))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_LoginInf)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Text_UsrName, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(PasswordField_Password))
                            .addComponent(Label_FormName))))
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 227, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_FormName)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_UsrName)
                    .addComponent(Text_UsrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Password)
                    .addComponent(PasswordField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Button_Submit)
                .addGap(18, 18, 18)
                .addComponent(Label_LoginInf)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_SubmitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Button_SubmitActionPerformed
    {//GEN-HEADEREND:event_Button_SubmitActionPerformed
        // TODO add your handling code here:
        try
        {
            String dbURL = "jdbc:sqlserver://localhost:1433;databaseName=fastfood;integratedSecurity=true";
            Connection conn = DriverManager.getConnection(dbURL);
            String query = "Select * from nhanvien where username_nv = ? and password_nv = ?";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1, Text_UsrName.getText());
            pst.setString(2, PasswordField_Password.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next())
            {
                TableManagement f = new TableManagement(rs.getString("fullname"), rs.getInt("id_nhanvien"));
                conn.close();
                this.setVisible(false);
                f.setVisible(true);
            } else
            {
                JOptionPane.showMessageDialog(rootPane, "Wrong username or password");
                conn.close();
            }
        } catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_Button_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Submit;
    private javax.swing.JLabel Label_FormName;
    private javax.swing.JLabel Label_LoginInf;
    private javax.swing.JLabel Label_Password;
    private javax.swing.JLabel Label_UsrName;
    private javax.swing.JPasswordField PasswordField_Password;
    private javax.swing.JTextField Text_UsrName;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
