/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fastfood;

import ModelObject.Product;
import ModelObject.Table;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hieupt
 */
public class TableManagement extends javax.swing.JFrame
{

    /**
     * Creates new form TableManagement
     */
    public TableManagement(String user, int id)
    {
        initComponents();
        int[] _temp = new int[4];
        trangthai_table = _temp;
        this.current_user = user;
        current_table = 0;
        Label_current_user.setText("Welcome " + this.current_user);
        SetItemComboBox();
        jScrollPane1.setVisible(false);
        this.current_user_id = id;
        getTable_trangthai();
        if (this.current_user_id == 1)
        {
            Button_IncomeForm.setVisible(true);
        } else
        {
            Button_IncomeForm.setVisible(false);
        }
    }

    public void getTable_trangthai()
    {
        try
        {
            String dbURL = "jdbc:sqlserver://localhost:1433;databaseName=fastfood;integratedSecurity=true";
            Connection conn = DriverManager.getConnection(dbURL);
            String query = "Select * from Ban";
            PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            while (rs.next())
            {
                trangthai_table[rs.getInt("id_ban") - 1] = rs.getInt("trangthai");
                System.out.println(trangthai_table[rs.getInt("id_ban") - 1]);
            }
        } catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        if (trangthai_table[0] == 1)
        {
            Button_Table1.setEnabled(false);
        }
        if (trangthai_table[1] == 1)
        {
            Button_Table2.setEnabled(false);
        }
        if (trangthai_table[2] == 1)
        {
            Button_Table3.setEnabled(false);
        }
        if (trangthai_table[3] == 1)
        {
            Button_Table4.setEnabled(false);
        }
    }

    public void SetItemComboBox()
    {
        try
        {
            String dbURL = "jdbc:sqlserver://localhost:1433;databaseName=fastfood;integratedSecurity=true";
            Connection conn = DriverManager.getConnection(dbURL);
            String query = "Select tensanpham from sanpham";
            PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            while (rs.next())
            {
                ComboBox_ProductSelect.addItem(rs.getString("tensanpham"));
            }
        } catch (Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        Panel_TableList = new javax.swing.JPanel();
        Label_TableList = new javax.swing.JLabel();
        Button_Table1 = new javax.swing.JButton();
        Button_Table2 = new javax.swing.JButton();
        Button_Table3 = new javax.swing.JButton();
        Button_Table4 = new javax.swing.JButton();
        Panel_Order = new javax.swing.JPanel();
        Label_Order = new javax.swing.JLabel();
        Label_Product = new javax.swing.JLabel();
        Label_Customer = new javax.swing.JLabel();
        Label_Code = new javax.swing.JLabel();
        ComboBox_ProductSelect = new javax.swing.JComboBox<>();
        TextField_Customer = new javax.swing.JTextField();
        Label_Number = new javax.swing.JLabel();
        TextField_Number = new javax.swing.JTextField();
        TextField_Code = new javax.swing.JTextField();
        Button_SubmitOrder = new javax.swing.JButton();
        Panel_Bill = new javax.swing.JPanel();
        Label_BillOf = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_BillDetails = new javax.swing.JTable();
        Button_Pay = new javax.swing.JButton();
        Label_Total = new javax.swing.JLabel();
        Label_TotalAmount = new javax.swing.JLabel();
        Label_current_user = new javax.swing.JLabel();
        Button_IncomeForm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_TableList.setBackground(new java.awt.Color(153, 153, 255));
        Panel_TableList.setForeground(new java.awt.Color(51, 51, 255));
        Panel_TableList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Label_TableList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_TableList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_TableList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-food-service-40.png"))); // NOI18N
        Label_TableList.setText("Table  List");

        Button_Table1.setText("Table 1");
        Button_Table1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                Button_Table1MouseClicked(evt);
            }
        });

        Button_Table2.setText("Table 2");
        Button_Table2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                Button_Table2MouseClicked(evt);
            }
        });

        Button_Table3.setText("Table 3");
        Button_Table3.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                Button_Table3MouseClicked(evt);
            }
        });

        Button_Table4.setText("Table 4");
        Button_Table4.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                Button_Table4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_TableListLayout = new javax.swing.GroupLayout(Panel_TableList);
        Panel_TableList.setLayout(Panel_TableListLayout);
        Panel_TableListLayout.setHorizontalGroup(
            Panel_TableListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_TableListLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(Panel_TableListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Button_Table3)
                    .addComponent(Button_Table1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addGroup(Panel_TableListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_Table2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Button_Table4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_TableListLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label_TableList, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        Panel_TableListLayout.setVerticalGroup(
            Panel_TableListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_TableListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_TableList)
                .addGap(42, 42, 42)
                .addGroup(Panel_TableListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Table1)
                    .addComponent(Button_Table2))
                .addGap(45, 45, 45)
                .addGroup(Panel_TableListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Table3)
                    .addComponent(Button_Table4))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        Panel_Order.setBackground(new java.awt.Color(255, 204, 204));

        Label_Order.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_Order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-food-50.png"))); // NOI18N
        Label_Order.setText("Order");

        Label_Product.setText("Product");

        Label_Customer.setText("Customer");

        Label_Code.setText("Code(Ship only)");

        Label_Number.setText("Number");

        Button_SubmitOrder.setText("Submit");
        Button_SubmitOrder.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                Button_SubmitOrderMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_OrderLayout = new javax.swing.GroupLayout(Panel_Order);
        Panel_Order.setLayout(Panel_OrderLayout);
        Panel_OrderLayout.setHorizontalGroup(
            Panel_OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_OrderLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(Panel_OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Product)
                    .addComponent(Label_Customer)
                    .addComponent(Label_Code)
                    .addComponent(Label_Number))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(Panel_OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_SubmitOrder)
                    .addGroup(Panel_OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ComboBox_ProductSelect, 0, 148, Short.MAX_VALUE)
                        .addComponent(TextField_Customer)
                        .addComponent(TextField_Code)
                        .addComponent(TextField_Number)))
                .addGap(38, 38, 38))
            .addGroup(Panel_OrderLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(Label_Order, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_OrderLayout.setVerticalGroup(
            Panel_OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_OrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Order, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(Panel_OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Product)
                    .addComponent(ComboBox_ProductSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(Panel_OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Number)
                    .addComponent(TextField_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(Panel_OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Label_Customer)
                    .addComponent(TextField_Customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Code)
                    .addComponent(TextField_Code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Button_SubmitOrder)
                .addGap(9, 9, 9))
        );

        Panel_Bill.setBackground(new java.awt.Color(204, 255, 204));

        Label_BillOf.setBackground(new java.awt.Color(204, 255, 255));
        Label_BillOf.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Label_BillOf.setForeground(new java.awt.Color(255, 51, 0));
        Label_BillOf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-bill-50.png"))); // NOI18N
        Label_BillOf.setText("BILL");

        Table_BillDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Tên", "Số lượng", "Giá(nghìn đồng)"
            }
        ));
        jScrollPane1.setViewportView(Table_BillDetails);

        Button_Pay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-money-50.png"))); // NOI18N
        Button_Pay.setText("Pay");
        Button_Pay.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                Button_PayMouseClicked(evt);
            }
        });

        Label_Total.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        Label_Total.setText("Total:");

        Label_TotalAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Label_current_user.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                Label_current_userMouseClicked(evt);
            }
        });

        Button_IncomeForm.setText("Income");
        Button_IncomeForm.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                Button_IncomeFormMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_BillLayout = new javax.swing.GroupLayout(Panel_Bill);
        Panel_Bill.setLayout(Panel_BillLayout);
        Panel_BillLayout.setHorizontalGroup(
            Panel_BillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BillLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_BillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_BillLayout.createSequentialGroup()
                        .addComponent(Label_current_user, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(Button_IncomeForm)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(Panel_BillLayout.createSequentialGroup()
                        .addGroup(Panel_BillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_BillOf, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_Pay)
                            .addGroup(Panel_BillLayout.createSequentialGroup()
                                .addComponent(Label_Total)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Label_TotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(194, Short.MAX_VALUE))))
        );
        Panel_BillLayout.setVerticalGroup(
            Panel_BillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BillLayout.createSequentialGroup()
                .addGroup(Panel_BillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Label_current_user, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_IncomeForm))
                .addGap(18, 18, 18)
                .addComponent(Label_BillOf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(Panel_BillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Label_Total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_TotalAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(Button_Pay, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Panel_Bill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel_TableList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_Order, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_TableList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_Order, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Panel_Bill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showbill_table(int id)
    {
        Label_BillOf.setText("Bill Of Table" + Integer.toString(id));
        int[] soluongsp = new int[ComboBox_ProductSelect.getItemCount() + 1];
        String[] tensp = new String[ComboBox_ProductSelect.getItemCount() + 1];
        int[] giasp = new int[ComboBox_ProductSelect.getItemCount() + 1];
        for (int i = 1; i < soluongsp.length; i++)
        {
            soluongsp[i] = 0;
            tensp[i] = "";
            giasp[i] = 0;
        }
        try
        {
            String dbURL = "jdbc:sqlserver://localhost:1433;databaseName=fastfood;integratedSecurity=true";
            Connection conn = DriverManager.getConnection(dbURL);
            String query = "select * from custom_order where fk_id_ban = ?";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setInt(1, id);
            ResultSet rs = pst.executeQuery();
            while (rs.next())
            {
                soluongsp[rs.getInt("fk_id_sp")] += rs.getInt("soluong");
            }
        } catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        try
        {
            String dbURL = "jdbc:sqlserver://localhost:1433;databaseName=fastfood;integratedSecurity=true";
            Connection conn = DriverManager.getConnection(dbURL);
            String query = "select * from sanpham";
            PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            while (rs.next())
            {
                if (soluongsp[rs.getInt("id_sp")] > 0)
                {
                    tensp[rs.getInt("id_sp")] = rs.getString("tensanpham");
                    giasp[rs.getInt("id_sp")] = rs.getInt("giathanh");
                }
            }
        } catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        ArrayList<hoadon> list = splist(tensp, soluongsp, giasp);
        DefaultTableModel model = (DefaultTableModel) Table_BillDetails.getModel();
        model.setRowCount(0);
        Object[] row = new Object[3];
        int sum = 0;
        for (int i = 0; i < list.size(); i++)
        {
            row[0] = list.get(i).getten();
            row[1] = list.get(i).getsoluong();
            row[2] = list.get(i).getgia();
            sum += list.get(i).getsoluong() * list.get(i).getgia();
            model.addRow(row);
        }
        Label_TotalAmount.setText(Integer.toString(sum) + "000");
        jScrollPane1.setVisible(true);
    }

    public ArrayList<hoadon> splist(String[] ten, int[] soluong, int[] gia)
    {
        ArrayList<hoadon> sp_list = new ArrayList<>();
        for (int i = 1; i < soluong.length; i++)
        {
            if (soluong[i] > 0)
            {
                hoadon _hoadon = new hoadon(ten[i], soluong[i], gia[i]);
                sp_list.add(_hoadon);
            }
        }
        return sp_list;
    }
    private void Button_Table1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Button_Table1MouseClicked
    {//GEN-HEADEREND:event_Button_Table1MouseClicked
        // TODO add your handling code here:
        if (Button_Table1.isEnabled())
        {
            current_table = 1;
            showbill_table(1);
        }
    }//GEN-LAST:event_Button_Table1MouseClicked

    private void Button_Table2MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Button_Table2MouseClicked
    {//GEN-HEADEREND:event_Button_Table2MouseClicked
        // TODO add your handling code here:
        if (Button_Table2.isEnabled())
        {
            current_table = 2;
            showbill_table(2);
        }
    }//GEN-LAST:event_Button_Table2MouseClicked

    private void Button_Table3MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Button_Table3MouseClicked
    {//GEN-HEADEREND:event_Button_Table3MouseClicked
        // TODO add your handling code here:
        if (Button_Table3.isEnabled())
        {
            current_table = 3;
            showbill_table(3);
        }
    }//GEN-LAST:event_Button_Table3MouseClicked

    private void Button_Table4MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Button_Table4MouseClicked
    {//GEN-HEADEREND:event_Button_Table4MouseClicked
        // TODO add your handling code here:
        if (Button_Table4.isEnabled())
        {
            current_table = 4;
            showbill_table(4);
        }
    }//GEN-LAST:event_Button_Table4MouseClicked

    private void Button_PayMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Button_PayMouseClicked
    {//GEN-HEADEREND:event_Button_PayMouseClicked
        // TODO add your handling code here:
        // xoa data o custom_order
        try
        {
            String dbURL = "jdbc:sqlserver://localhost:1433;databaseName=fastfood;integratedSecurity=true";
            Connection conn = DriverManager.getConnection(dbURL);
            String query = "delete from custom_order where fk_id_ban = ?";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setInt(1, this.current_table);
            ResultSet rs = pst.executeQuery();
        } catch (SQLException ex)
        {
        }
        // tra lai trang thai cua ban la trong
        disablebutton_table(this.current_table);
        try
        {
            String dbURL = "jdbc:sqlserver://localhost:1433;databaseName=fastfood;integratedSecurity=true";
            Connection conn = DriverManager.getConnection(dbURL);
            String query = "update ban set trangthai = 1 where id_ban = ?";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setInt(1, this.current_table);
            pst.executeUpdate();
        } catch (SQLException ex)
        {
        }
        trangthai_table[this.current_table - 1] = 1;
        
        //hien thi thong tin thong bao
        if (Label_TotalAmount.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Please Select A Table");
        } else
        {
            JOptionPane.showMessageDialog(rootPane, "Printing Bill");
        }
        jScrollPane1.setVisible(false);
        Label_TotalAmount.setText("");
    }//GEN-LAST:event_Button_PayMouseClicked

    private void Button_SubmitOrderMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Button_SubmitOrderMouseClicked
    {//GEN-HEADEREND:event_Button_SubmitOrderMouseClicked
        // TODO add your handling code here:
        String SelectedProduct = ComboBox_ProductSelect.getSelectedItem().toString();
        int NumberOfProduct = Integer.valueOf(TextField_Number.getText());
        int id_table = Integer.valueOf(TextField_Customer.getText());
        int product_id = 0;
        try
        {
            String dbURL = "jdbc:sqlserver://localhost:1433;databaseName=fastfood;integratedSecurity=true";
            Connection conn = DriverManager.getConnection(dbURL);
            String query = "Select id_sp from sanpham where tensanpham = ?";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1, SelectedProduct);
            ResultSet rs = pst.executeQuery();
            if (rs.next())
            {
                product_id = rs.getInt("id_sp");
            }
        } catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(rootPane, ex);
        }

        InsertProduct(id_table, product_id, NumberOfProduct);
        current_table = id_table;
        getTable_trangthai();
        showbill_table(id_table);
//        String Customer = TextField_Customer.getText().toUpperCase();
//        JOptionPane.showMessageDialog(rootPane, Customer + " ordered" + " " + NumberOfProduct + " " + SelectedProduct);
    }//GEN-LAST:event_Button_SubmitOrderMouseClicked

    private void Label_current_userMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Label_current_userMouseClicked
    {//GEN-HEADEREND:event_Label_current_userMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        LoginForm f = new LoginForm();
        f.setVisible(true);
    }//GEN-LAST:event_Label_current_userMouseClicked

    private void Button_IncomeFormMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Button_IncomeFormMouseClicked
    {//GEN-HEADEREND:event_Button_IncomeFormMouseClicked
        // TODO add your handling code here:
        IncomeSummary f = new IncomeSummary(ComboBox_ProductSelect.getItemCount());
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Button_IncomeFormMouseClicked

    public void enablebutton_table(int id)
    {
        if (id == 1)
        {
            Button_Table1.setEnabled(true);
        } else if (id == 2)
        {
            Button_Table2.setEnabled(true);
        } else if (id == 3)
        {
            Button_Table3.setEnabled(true);
        } else
        {
            Button_Table4.setEnabled(true);
        }
    }

    public void disablebutton_table(int id)
    {
        if (id == 1)
        {
            Button_Table1.setEnabled(false);
        } else if (id == 2)
        {
            Button_Table2.setEnabled(false);
        } else if (id == 3)
        {
            Button_Table3.setEnabled(false);
        } else
        {
            Button_Table4.setEnabled(false);
        }
    }

    public void InsertProduct(int id_table, int product_id, int quantity)
    {        //danh dau ban da dat: 1(bantrong) 0(dadat)
        if (trangthai_table[id_table - 1] == 1)
        {
            enablebutton_table(id_table);
            try
            {
                String dbURL = "jdbc:sqlserver://localhost:1433;databaseName=fastfood;integratedSecurity=true";
                Connection conn = DriverManager.getConnection(dbURL);
                String query = "update ban set trangthai = 0 where id_ban = ?";
                PreparedStatement pst = conn.prepareStatement(query);
                pst.setInt(1, id_table);
                pst.executeUpdate();
            } catch (SQLException ex)
            {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
            trangthai_table[id_table - 1] = 0;

            //insert vao table Bill lan` dau` dung` ban`
            try
            {
                String dbURL = "jdbc:sqlserver://localhost:1433;databaseName=fastfood;integratedSecurity=true";
                Connection conn = DriverManager.getConnection(dbURL);
                String query = "insert into Bill(FK_id_table, FK_id_nhanvien) values (?,?)";
                PreparedStatement pst = conn.prepareStatement(query);
                pst.setInt(1, id_table);
                pst.setInt(2, this.current_user_id);
                pst.executeUpdate();
            } catch (SQLException ex)
            {
                JOptionPane.showMessageDialog(rootPane, ex);
            }
        }
        try
        {
            String dbURL = "jdbc:sqlserver://localhost:1433;databaseName=fastfood;integratedSecurity=true";
            Connection conn = DriverManager.getConnection(dbURL);
            String query = "insert into custom_order(fk_id_ban, fk_id_sp, soluong, ngay) values (?,?,?,?)";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setInt(1, id_table);
            pst.setInt(2, product_id);
            pst.setInt(3, quantity);
            pst.setDate(4, java.sql.Date.valueOf(LocalDate.now()));
            pst.executeUpdate();
        } catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        try
        {
            String dbURL = "jdbc:sqlserver://localhost:1433;databaseName=fastfood;integratedSecurity=true";
            Connection conn = DriverManager.getConnection(dbURL);
            String query = "insert into thongke(fk_id_sp, soluong, ngay) values (?,?,?)";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setInt(1, product_id);
            pst.setInt(2, quantity);
            pst.setDate(3, java.sql.Date.valueOf(LocalDate.now()));
            pst.executeUpdate();
        } catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(TableManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(TableManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(TableManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(TableManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new TableManagement("", 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_IncomeForm;
    private javax.swing.JButton Button_Pay;
    private javax.swing.JButton Button_SubmitOrder;
    private javax.swing.JButton Button_Table1;
    private javax.swing.JButton Button_Table2;
    private javax.swing.JButton Button_Table3;
    private javax.swing.JButton Button_Table4;
    private javax.swing.JComboBox<String> ComboBox_ProductSelect;
    private javax.swing.JLabel Label_BillOf;
    private javax.swing.JLabel Label_Code;
    private javax.swing.JLabel Label_Customer;
    private javax.swing.JLabel Label_Number;
    private javax.swing.JLabel Label_Order;
    private javax.swing.JLabel Label_Product;
    private javax.swing.JLabel Label_TableList;
    private javax.swing.JLabel Label_Total;
    private javax.swing.JLabel Label_TotalAmount;
    private javax.swing.JLabel Label_current_user;
    private javax.swing.JPanel Panel_Bill;
    private javax.swing.JPanel Panel_Order;
    private javax.swing.JPanel Panel_TableList;
    private javax.swing.JTable Table_BillDetails;
    private javax.swing.JTextField TextField_Code;
    private javax.swing.JTextField TextField_Customer;
    private javax.swing.JTextField TextField_Number;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    String current_user;
    int current_user_id;
    int[] trangthai_table;
    int current_table;
}
